### ISSUE TITLE
Entities renamed / unavaible

### ISSUE THREAD

**Issue by pergolafabio** [pawlizio/my_velux#39]
Hey, not sure what happened, but all my entities were unavaible? Seems theye were doubled in HA
I think maybe of the last release?

i had like 
cover.velux .. => unavaible
was renamed to:
cover.velux_2

had to remove all the unavaible entities and renamed the new ones to the old ones

**Comment by pawlizio** [comment]
Ah yes, I also noticed that. Background is that give assistant want a unique_id of type string, however till now we simply used either serial number and it not available the node_id. Nope_id however was a number. So this is mainly caused to follow strict typing.

**Comment by pergolafabio** [comment]
I saw you were also helping to make an official PR ? Is this custom in final stages?

**Comment by pawlizio** [comment]
Yes, I made all the changes also on this custom, so they are in line to what I planned to merge to HA. However this PR was too big and there were other PRs running already for longer time.

**Comment by thunderj27** [comment]
Hi All, 
I had the same issue.
I also had to correct all my automations and scripts after renaming entitites because they were using device_id (which have also changed). 
_PS: My automations and scripts are now using with entity_ids. I believe that it will be easier to maintain if it happens again._
