### ISSUE TITLE
After some time my devices dissappear

### ISSUE THREAD

**Issue by evilmumi** [pawlizio/my_velux#40]
After some time my devices dissappear  then i press reboot KLF200
After it, i have each device 2 times.
What can I do?
with _2

**Comment by pawlizio** [comment]
Yes, this issue is the same as reported here: https://github.com/pawlizio/my_velux/issues/39
Finally the covers does not provide a serial number, so a node id (simple integer number) was used in the past to identify the covers. In my last release I enabled full typing support and figured our that HomeAssistant requires a string (Text) as unique_id, not a number. That's why now the entities are created new but the old one still are in the database. Please remove the one without "_2" at the end and rename all with "_2" (just remove the "_2") please. Ad the moment I do not have another way to fix this.

**Comment by pawlizio** [comment]
This should not repeat, so only once after last update and reboot.

**Comment by evilmumi** [comment]
But not after every reboot or?

**Comment by pawlizio** [comment]
No, the unique_id logic was just changed in the last update. It will not happen after each reboot, just after the first after the last update installation.

**Comment by evilmumi** [comment]
Today I've got 2 devices back one with entities one without but with connection to my automations.
![image](https://github.com/pawlizio/my_velux/assets/23313699/192fb8ee-a1f3-416b-8c9e-2d155f7bf549)
